# run docker build -t dev:22.04 -f Dockerfile.ubuntu.dev .
# run docker build --build-arg USER_ID=$uid --build-arg GROUP_ID=$gid -t dev:22.04 -f Dockerfile.ubuntu.dev .
FROM buildpack-deps:jammy

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update -y

# build essential
RUN apt install -y --no-install-recommends clang lld
RUN apt install -y --no-install-recommends gcc g++

# tools
RUN apt install -y sudo curl git fzf wget make vim ripgrep

# basic
RUN apt install -y bzip2 ca-certificates

# languages
RUN apt install -y python3-dev python3-pip
RUN apt install -y nodejs npm
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -s | sh -s -- -y

# conda
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh && \
    chmod +x miniconda.sh && \
    ./miniconda.sh -b -p /opt/miniconda && \
    rm miniconda.sh

ENV PATH="/opt/miniconda/bin:$PATH"
ENV PATH="/root/.local/bin:/root/.cargo/bin:$PATH"

# zsh
RUN apt install -y zsh-autosuggestions zsh-syntax-highlighting zsh
# ohmyzsh
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended

# lazygit
RUN LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*') && \
    curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz" && \
    tar xf lazygit.tar.gz lazygit && \
    sudo install lazygit /usr/local/bin && \
    rm lazygit.tar.gz

# neovim
RUN apt install -y software-properties-common && \
    add-apt-repository ppa:neovim-ppa/unstable -y && \
    apt update -y && \
    apt install -y neovim

# miniconda ---- not needed
# RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
#     chmod +x Miniconda3-latest-Linux-x86_64.sh && \
#     ./Miniconda3-latest-Linux-x86_64.sh -b -p /opt/miniconda && \
#     rm Miniconda3-latest-Linux-x86_64.sh

ENV PATH /opt/miniconda/bin:$PATH

RUN /opt/miniconda/bin/conda init zsh

# lunarvim
RUN curl -LSs  https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh | bash -s -- --yes

RUN rm -rf /root/.config/lvim && git clone https://github.com/meteora211/lvim.git ~/.config/lvim
